spring.application.name=financial-management

# ==================== SQL Server DataSource ====================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FinanceDB;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8;sendStringParametersAsUnicode=true
spring.datasource.username=admin
spring.datasource.password=Adunani27
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==================== JPA / Hibernate ====================
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==================== JWT ====================
jwt.secret=FinancialManagementSecretKey2024VeryLongStringMinimum256Bits
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# ==================== Gmail SMTP ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ntri3882@gmail.com
spring.mail.password=aajl zvvm slds hxly
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# ==================== OTP ====================
otp.expiration-minutes=5
otp.resend-cooldown-seconds=60

# ==================== Server ====================
server.address=0.0.0.0
server.port=8080
